// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../../../spiel/build/libspielprovider
// DO NOT EDIT

mod stream_writer;
pub use self::stream_writer::StreamWriter;

mod enums;
pub use self::enums::EventType;

mod flags;
pub use self::flags::VoiceFeature;

