// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../../../../spiel/build/libspeechprovider
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) SPEECH_PROVIDER_CHUNK_TYPE_AUDIO);
    PRINT_CONSTANT((gint) SPEECH_PROVIDER_CHUNK_TYPE_EVENT);
    PRINT_CONSTANT((gint) SPEECH_PROVIDER_CHUNK_TYPE_NONE);
    PRINT_CONSTANT((gint) SPEECH_PROVIDER_EVENT_TYPE_MARK);
    PRINT_CONSTANT((gint) SPEECH_PROVIDER_EVENT_TYPE_NONE);
    PRINT_CONSTANT((gint) SPEECH_PROVIDER_EVENT_TYPE_RANGE);
    PRINT_CONSTANT((gint) SPEECH_PROVIDER_EVENT_TYPE_SENTENCE);
    PRINT_CONSTANT((gint) SPEECH_PROVIDER_EVENT_TYPE_WORD);
    PRINT_CONSTANT(SPEECH_PROVIDER_STREAM_PROTOCOL_VERSION);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_EVENTS_RANGE);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_EVENTS_SENTENCE);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_EVENTS_SSML_MARK);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_EVENTS_WORD);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_NONE);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_BREAK);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_EMPHASIS);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_PHONEME);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_PROSODY);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_SAY_AS_CARDINAL);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_SAY_AS_CHARACTERS);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_SAY_AS_CHARACTERS_GLYPHS);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_SAY_AS_CURRENCY);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_SAY_AS_DATE);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_SAY_AS_ORDINAL);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_SAY_AS_TELEPHONE);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_SAY_AS_TIME);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_SENTENCE_PARAGRAPH);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_SUB);
    PRINT_CONSTANT((guint) SPEECH_PROVIDER_VOICE_FEATURE_SSML_TOKEN);
    return 0;
}
