// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../../../../spiel/build/libspielprovider
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) SPIEL_PROVIDER_CHUNK_TYPE_AUDIO);
    PRINT_CONSTANT((gint) SPIEL_PROVIDER_CHUNK_TYPE_EVENT);
    PRINT_CONSTANT((gint) SPIEL_PROVIDER_CHUNK_TYPE_NONE);
    PRINT_CONSTANT((gint) SPIEL_PROVIDER_EVENT_TYPE_MARK);
    PRINT_CONSTANT((gint) SPIEL_PROVIDER_EVENT_TYPE_NONE);
    PRINT_CONSTANT((gint) SPIEL_PROVIDER_EVENT_TYPE_RANGE);
    PRINT_CONSTANT((gint) SPIEL_PROVIDER_EVENT_TYPE_SENTENCE);
    PRINT_CONSTANT((gint) SPIEL_PROVIDER_EVENT_TYPE_WORD);
    PRINT_CONSTANT(SPIEL_PROVIDER_STREAM_PROTOCOL_VERSION);
    return 0;
}
