// This file was generated by gir (https://github.com/gtk-rs/gir)
// from /usr/share/gir-1.0
// from ../../../../spiel/build/libspielprovider
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "SpielProviderChunkType", sizeof(SpielProviderChunkType), alignof(SpielProviderChunkType));
    printf("%s;%zu;%zu\n", "SpielProviderEventData", sizeof(SpielProviderEventData), alignof(SpielProviderEventData));
    printf("%s;%zu;%zu\n", "SpielProviderEventType", sizeof(SpielProviderEventType), alignof(SpielProviderEventType));
    printf("%s;%zu;%zu\n", "SpielProviderStreamHeader", sizeof(SpielProviderStreamHeader), alignof(SpielProviderStreamHeader));
    printf("%s;%zu;%zu\n", "SpielProviderStreamReaderClass", sizeof(SpielProviderStreamReaderClass), alignof(SpielProviderStreamReaderClass));
    printf("%s;%zu;%zu\n", "SpielProviderStreamWriterClass", sizeof(SpielProviderStreamWriterClass), alignof(SpielProviderStreamWriterClass));
    printf("%s;%zu;%zu\n", "SpielProviderVoiceFeature", sizeof(SpielProviderVoiceFeature), alignof(SpielProviderVoiceFeature));
    return 0;
}
